Added iframephone calls to inform LARA if document is dirty [#130837611]
concord-consortium/labbook pull request #2
Opened 2017-01-11 18:02 UTC by dougmartin

2017-01-11 18:02 UTC, dougmartin commented
@scytacki For review with https://github.com/concord-consortium/lara/pull/238

2017-01-18 15:46 UTC, scytacki requested changes
seems like disconnect message isn't handled.

2017-01-18 15:46 UTC, scytacki commented on app/views/snapshots/_form.html.haml
> +                  phone.post('disconnect');
I don't see a handler for disconnect in LARA.  Is it necessary to disconnect in this case?
If connected LARA will send the canClose message. And then the labbook will immediately respond with 'close'.

2017-01-18 16:16 UTC, scytacki commented
This looks good to me. @knowuh do you want to take a quick look?

2017-01-18 21:45 UTC, knowuh commented
Took me a while to figure out what this was all about. In the end, it looks fine to me.  👍

2017-01-18 21:46 UTC, scytacki approved these changes

2017-01-18 21:47 UTC, scytacki commented
OK I'm going to wait to merge this until a small UI fix is in regarding a browse button on firefox.

2017-01-19 01:35 UTC, merged

2017-01-19 04:40 UTC, scytacki commented
Heroku staging server is having trouble building this. I haven't investigated yet.